blank_issues_enabled: false
contact_links:
  - name: General Discussion
    url: https://github.com/cmbays/print-4ink/discussions
    about: Questions, ideas, or topics that don't fit an issue template
